# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.8

  http: ^1.2.2

  csv: ^6.0.0

  lottie: ^3.1.2

  hive: ^2.2.3

  hive_flutter: ^1.1.0

  google_mobile_ads: ^5.1.0

  firebase_core: ^3.3.0

  firebase_remote_config: ^5.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name
  change_app_package_name: ^1.3.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/animations/
    - assets/images/
    - assets/flags/