// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb0noOzybDnVn7GG3LsusxqDvO4cAj6Gc',
    appId: '1:196490481250:android:5f09eb7e4c91bccb1d0b3b',
    messagingSenderId: '196490481250',
    projectId: 'free-vpn-32f5a',
    storageBucket: 'free-vpn-32f5a.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8F6CNptpMUwFpMhhr-gqKCG7ieD_FrS0',
    appId: '1:196490481250:web:bf5a4ee5626f32d91d0b3b',
    messagingSenderId: '196490481250',
    projectId: 'free-vpn-32f5a',
    authDomain: 'free-vpn-32f5a.firebaseapp.com',
    storageBucket: 'free-vpn-32f5a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8F6CNptpMUwFpMhhr-gqKCG7ieD_FrS0',
    appId: '1:196490481250:web:07de8d5b910edac21d0b3b',
    messagingSenderId: '196490481250',
    projectId: 'free-vpn-32f5a',
    authDomain: 'free-vpn-32f5a.firebaseapp.com',
    storageBucket: 'free-vpn-32f5a.appspot.com',
  );

}